github.com:
    users:
        RajaMuhammadAwais:
            oauth_token: ghu_SYW2ADEjDMkEpmgy0X2nXlZ6RbAYiu3frKdX
    oauth_token: ghu_SYW2ADEjDMkEpmgy0X2nXlZ6RbAYiu3frKdX
    user: RajaMuhammadAwais
